// examples/threaditjs/vue/components/home.vue
<template>
    <app-layout v-bind:load="load">
        <thread-preview
            v-for="thread in threads"
            v-bind:key="thread.id"
            v-bind:thread="thread"
        ></thread-preview>
        <new-thread v-on:save="save"></new-thread>
    </app-layout>
</template>

<script>
import AppLayout from "./app-layout.vue"
import ThreadPreview from "./thread-preview.vue"
import * as api from "../api.mjs"

export default {
    data() {
        return {threads: []}
    },

    methods: {
        load(signal) {
            return api.home({signal}).then((response) => {
                document.title = "ThreaditJS: Vue | Home"
                this.threads = response.data
            })
        },

        save(thread) {
            this.threads.push(thread)
        },
    },

    components: {
        AppLayout,
        ThreadPreview,
    },
}
</script>

// examples/threaditjs/react-hooks-jsx/components/Home.js
import React, {useState} from "react"
import api from "../api.js"
import Layout from "./Layout.js"
import ThreadPreview from "./ThreadPreview.js"
import NewThread from "./NewThread.js"

export default function Home() {
    const [threads, setThreads] = useState([])

    return (
        <Layout
            load={(signal) => api.home({signal}).then((response) => {
                document.title = "ThreaditJS: React | Home"
                setThreads(response.data)
            })}
            render={() => <>
                {threads.map((thread) => (
                    <ThreadPreview key={thread.id} thread={thread} />
                ))}
                <NewThread onSave={(thread) => setThreads([...threads, thread])} />
            </>}
        />
    )
}
