// examples/threaditjs/svelte/components/reply.svelte
<script>
import * as api from "../api.mjs"
export let node

let replying = false
let comment = ""

$: preview = T.previewComment(comment)

async function submit() {
    const {data} = await api.newComment(comment, node.id)
    node.children.push(data)
    replying = false
    comment = ""
}
</script>

{#if replying}
    <form on:submit|preventDefault|stopPropagation={submit}>
        <textarea bind:value={comment}></textarea>
        <input type="submit" value="Reply!">
        <div class="preview">{@html preview}</div>
    </form>
{:else}
    <a on:click|preventDefault|stopPropagation={replying = true}>Reply!</a>
{/if}

// examples/threaditjs/react-hooks-jsx/components/Reply.js
import React, {useState} from "react"
import api from "../api.js"

export default function Reply({node}) {
    const [newComment, setNewComment] = useState()

    if (newComment != null) {
        return (
            <form onSubmit={(ev) => {
                ev.preventDefault()
                ev.stopPropagation()
                api.newComment(newComment, node.id).then((response) => {
                    node.children.push(response.data)
                    setNewComment()
                })
            }}>
                <textarea
                    value={newComment}
                    onInput={(ev) => setNewComment(ev.target.value)}
                />
                <input type="submit" value="Reply!" />
                <div
                    className="preview"
                    dangerouslySetInnerHTML={{
                        __html: T.previewComment(newComment),
                    }}
                />
            </form>
        )
    } else {
        return (
            <a onClick={(ev) => {
                ev.preventDefault()
                ev.stopPropagation()
                setNewComment("")
            }}>
                Reply!
            </a>
        )
    }
}
