// examples/threaditjs/svelte/components/layout.svelte
<script>
import {Navigate} from "svelte-router-spa"
import {onMount} from "svelte"

export let load
let state = "loading"
let value

onMount(() => {
    const controller = new AbortController()
    load(controller.signal).then(
        (v) => { state = "ready"; value = v },
        (e) => { state = e.status === 404 ? "notFound" : "error" }
    )
    return () => controller.abort()
})
</script>

<p class="head_links">
    <a href="https://github.com/isiahmeadows/mithril.js/tree/redesign/examples/threaditjs/svelte">Source</a> |
    <a href="https://threaditjs.com">ThreaditJS: Home</a>
</p>
<h2>
    <Navigate to="/">ThreaditJS: Svelte</Navigate>
</h2>
<div class="main">
    {#if state === "loading"}
        <h2>Loading</h2>
    {:else if state === "notFound"}
        <h2>Not found! Don't try refreshing!</h2>
    {:else if state === "error"}
        <h2>Error! Try refreshing.</h2>
    {:else}
        <slot></slot>
    {/if}
</div>

// examples/threaditjs/react-jsx/components/Layout.js
import React from "react"
import Header from "./Header"

export default class Layout extends React.Component {
    state = {
        state: "loading",
        value: null,
    }
    controller = new AbortController()

    componentDidMount() {
        this.props.load(this.controller.signal).then((value) => {
            document.title = "ThreaditJS: React | Home"
            this.setState({state: "ready", value})
        }, (e) => {
            this.setState({state: e.status === 404 ? "notFound" : "error"})
        })
    }

    componentWillUnmount() {
        this.controller.abort()
    }

    renderPage() {
        switch (this.state.state) {
        case "loading":
            return <h2>Loading</h2>

        case "notFound":
            return <h2>Not found! Don&apos;t try refreshing!</h2>

        case "error":
            return <h2>Error! Try refreshing.</h2>

        default:
            return this.props.render(this.state.value)
        }
    }

    render() {
        return <>
            <Header />
            <div className="main">{this.renderPage()}</div>
        </>
    }
}
