// examples/threaditjs/svelte/components/reply.svelte
<script>
import * as api from "../api.mjs"
export let node

let replying = false
let comment = ""

$: preview = T.previewComment(comment)

async function submit() {
    const {data} = await api.newComment(comment, node.id)
    node.children.push(data)
    replying = false
    comment = ""
}
</script>

{#if replying}
    <form on:submit|preventDefault|stopPropagation={submit}>
        <textarea bind:value={comment}></textarea>
        <input type="submit" value="Reply!">
        <div class="preview">{@html preview}</div>
    </form>
{:else}
    <a on:click|preventDefault|stopPropagation={replying = true}>Reply!</a>
{/if}

// examples/threaditjs/react-jsx/components/Reply.js
import React from "react"
import api from "../api.js"

export default class Reply extends React.Component {
    state = {
        newComment: null,
    }

    render() {
        const {newComment} = this.state
        const {node} = this.props

        if (newComment != null) {
            return (
                <form onSubmit={(ev) => {
                    ev.preventDefault()
                    ev.stopPropagation()
                    api.newComment(newComment, node.id).then((response) => {
                        node.children.push(response.data)
                        this.setState({newComment: null})
                    })
                }}>
                    <textarea value={newComment} onInput={(ev) => {
                        this.setState({newComment: ev.target.value})
                    }} />
                    <input type="submit" value="Reply!" />
                    <div className="preview" dangerouslySetInnerHTML={{
                        __html: T.previewComment(newComment),
                    }} />
                </form>
            )
        } else {
            return (
                <a onClick={(ev) => {
                    ev.preventDefault()
                    ev.stopPropagation()
                    this.setState({newComment: ""})
                }}>
                    Reply!
                </a>
            )
        }
    }
}
