// examples/threaditjs/svelte/components/thread-node.svelte
<script>
import Reply from "./reply.svelte"
export let node
</script>

<div class="comment">
    <p>{@html node.text}</p>
    <div class="reply"><Reply {node} /></div>
    <div class="children">
        {#each node.children as child (child.id)}
            <svelte:self node={child} />
        {/each}
    </div>
</div>

// examples/threaditjs/react-jsx/components/ThreadNode.js
import React from "react"
import Reply from "./Reply.js"

export default function ThreadNode({node}) {
    return (
        <div className="comment">
            <p dangerouslySetInnerHTML={{__html: node.text}} />
            <div className="reply"><Reply node={node} /></div>
            <div className="children">
                {node.children.map((child) => (
                    <ThreadNode key={child.id} node={child} />
                ))}
            </div>
        </div>
    )
}
