// examples/threaditjs/react-hooks-jsx/components/Layout.js
import React, {useState, useEffect} from "react"
import Header from "./Header"

export default function Layout({load, onLoad, render}) {
    const [[state, value], set] = useState(["pending"])

    useEffect(() => {
        const controller = new AbortController()
        new Promise((resolve) => resolve(onLoad(controller.signal))).then(
            (response) => set(["ready", response]),
            (e) => set([e.status === 404 ? "missing" : "error", null])
        )
        return () => controller.abort()
    }, []) // eslint-disable-line react-hooks/exhaustive-deps

    let view

    switch (state) {
    case "pending": view = <h2>Loading</h2>; break
    case "ready": view = render(value); break
    case "missing": view = <h2>Not found! Don&apos;t try refreshing!</h2>; break
    case "error": view = <h2>Error! Try refreshing.</h2>; break
    }

    return <>
        <Header />
        <div className="main">{view}</div>
    </>
}

// examples/threaditjs/svelte/components/layout.svelte
<script>
import {Navigate} from "svelte-router-spa"
import {onMount} from "svelte"

export let load
let state = "loading"
let value

onMount(() => {
    const controller = new AbortController()
    load(controller.signal).then(
        (v) => { state = "ready"; value = v },
        (e) => { state = e.status === 404 ? "notFound" : "error" }
    )
    return () => controller.abort()
})
</script>

<p class="head_links">
    <a href="https://github.com/isiahmeadows/mithril.js/tree/redesign/examples/threaditjs/svelte">Source</a> |
    <a href="https://threaditjs.com">ThreaditJS: Home</a>
</p>
<h2>
    <Navigate to="/">ThreaditJS: Svelte</Navigate>
</h2>
<div class="main">
    {#if state === "loading"}
        <h2>Loading</h2>
    {:else if state === "notFound"}
        <h2>Not found! Don't try refreshing!</h2>
    {:else if state === "error"}
        <h2>Error! Try refreshing.</h2>
    {:else}
        <slot></slot>
    {/if}
</div>
