// examples/threaditjs/vue/components/new-thread.vue
<template>
    <form v-bind:submit.prevent.stop="submit">
        <textarea v-model="comment"></textarea>
        <input type="submit" value="Post!">
    </form>
</template>

<script>
import * as api from "../api.mjs"

export default {
    data() {
        return {comment: ""}
    },

    methods: {
        async submit() {
            const {data: thread} = await api.newThread(this.comment)
            this.comment = ""
            this.$emit("save", thread)
        },
    }
}
</script>

// examples/threaditjs/svelte/components/new-thread.svelte
<script>
import * as api from "../api.mjs"
import {createEventDispatcher} from "svelte"

const dispatch = createEventDispatcher()
let comment = ""

async function submit() {
    const {data: thread} = await api.newThread(comment)
    comment = ""
    dispatch("save", thread)
}
</script>

<form on:submit|preventDefault|stopPropagation="submit">
    <textarea bind:value={comment}></textarea>
    <input type="submit" value="Post!">
</form>
