// examples/threaditjs/react-hooks-jsx/components/NewThread.js
import React, {useState} from "react"
import api from "../api.js"

export default function NewThread({onSave}) {
    const [value, setValue] = useState("")

    return (
        <form onSubmit={(ev) => {
            ev.preventDefault()
            ev.stopPropagation()
            api.newThread(value).then(({data: thread}) => {
                if (onSave) onSave(thread)
                setValue("")
            })
        }}>
            <textarea
                value={value}
                onInput={(ev) => setValue(ev.target.value)}
            />
            <input type="submit" value="Post!" />
        </form>
    )
}

// examples/threaditjs/svelte/components/new-thread.svelte
<script>
import * as api from "../api.mjs"
import {createEventDispatcher} from "svelte"

const dispatch = createEventDispatcher()
let comment = ""

async function submit() {
    const {data: thread} = await api.newThread(comment)
    comment = ""
    dispatch("save", thread)
}
</script>

<form on:submit|preventDefault|stopPropagation="submit">
    <textarea bind:value={comment}></textarea>
    <input type="submit" value="Post!">
</form>
