// examples/threaditjs/mithril-redesign-jsx/components/Thread.jsx
import {m} from "mithril"
import * as api from "../api.mjs"
import Layout from "./Layout.jsx"
import ThreadNode from "./ThreadNode.jsx"

export default function Thread({id}, info) {
    if (info.isInitial()) T.time("Thread render")

    return <>
        {info.isInitial() && m.capture(() => T.timeEnd("Thread render"))}
        <Layout
            id={id}
            load={async (signal) => {
                const {root} = await api.thread(id, {signal})
                document.title = `ThreaditJS: Mithril | ${T.trimTitle(root.text)}`
                return root
            }}
            view={(node) => <ThreadNode node={node} />}
        />
    </>
}

// examples/threaditjs/svelte/components/thread.svelte
<script>
import Layout from "./layout.svelte"
import ThreadNode from "./thread-node.svelte"
import * as api from "../api.mjs"

export let currentRoute
let root

$: title = T.trimTitle(root.text)

async function load(signal) {
    root = (await api.thread(currentRoute.namedParams.id, {signal})).root
}
</script>

<svelte:head>
    <title>ThreaditJS: Svelte | {title}</title>
</svelte:head>

<Layout {load}>
    <ThreadNode node={root} />
</Layout>
