// examples/threaditjs/svelte/components/home.svelte
<script>
import Layout from "./layout.svelte"
import * as api from "../api.mjs"

let threads = []

async function load(signal) {
    threads = (await api.home({signal})).data
}
</script>

<svelte:head>
    <title>ThreaditJS: Svelte | Home</title>
</svelte:head>

<Layout {load}>
    {#each threads as thread (thread.id)}
        <ThreadPreview {thread} />
    {/each}
    <NewThread on:save={() => threads = [...threads, thread]} />
</Layout>

// examples/threaditjs/mithril-redesign-dsl-jsx/components/Home.jsx
import {m, component} from "mithril"
import * as api from "../api.mjs"
import {Layout} from "./Layout.jsx"
import {ThreadPreview} from "./ThreadPreview.jsx"
import {NewThread} from "./NewThread.jsx"

export const Home = component(() => (
    <Layout
        load={(_, signal) => api.home({signal})}
        view={({data: threads}) => {
            document.title = "ThreaditJS: Mithril | Home"

            return <>
                {m.each(threads, "id", (thread) => (
                    <ThreadPreview thread={thread} />
                ))}
                <NewThread onsave={(thread) => threads.push(thread)} />
            </>
        }}
    />
))
