// examples/threaditjs/svelte/components/thread.svelte
<script>
import Layout from "./layout.svelte"
import ThreadNode from "./thread-node.svelte"
import * as api from "../api.mjs"

export let currentRoute
let root

$: title = T.trimTitle(root.text)

async function load(signal) {
    root = (await api.thread(currentRoute.namedParams.id, {signal})).root
}
</script>

<svelte:head>
    <title>ThreaditJS: Svelte | {title}</title>
</svelte:head>

<Layout {load}>
    <ThreadNode node={root} />
</Layout>

// examples/threaditjs/mithril-redesign-dsl-jsx/components/Thread.jsx
import {m, component, whenReady, isInitial} from "mithril"
import * as api from "../api.mjs"
import {Layout} from "./Layout.jsx"
import {ThreadNode} from "./ThreadNode.jsx"

export const Thread = component(({id}) => {
    if (isInitial()) {
        T.time("Thread render")
        whenReady(() => T.timeEnd("Thread render"))
    }

    return <Layout
        id={id}
        load={(_, signal) => api.thread(id, {signal})}
        view={({root: node}) => {
            const title = T.trimTitle(node.text)
            document.title = `ThreaditJS: Mithril | ${title}`
            return <ThreadNode node={node} />
        }}
    />
})
