// examples/threaditjs/svelte/components/new-thread.svelte
<script>
import * as api from "../api.mjs"
import {createEventDispatcher} from "svelte"

const dispatch = createEventDispatcher()
let comment = ""

async function submit() {
    const {data: thread} = await api.newThread(comment)
    comment = ""
    dispatch("save", thread)
}
</script>

<form on:submit|preventDefault|stopPropagation="submit">
    <textarea bind:value={comment}></textarea>
    <input type="submit" value="Post!">
</form>

// examples/threaditjs/mithril-redesign-jsx/components/NewThread.jsx
import {m} from "mithril"
import * as api from "../api.mjs"

export default function NewThread({on}, info) {
    const text = info.init(() => "")

    async function saveThread(ev, capture) {
        capture.event()
        const {data: thread} = await api.newThread(info.state)
        on.save(thread)
        info.state = ""
    }

    return <form on={{submit: saveThread}}>
        <textarea value={text} on={{input: ["value", (t) => info.state = t]}} />
        <input type="submit" value="Post!" />
    </form>
}
