// examples/threaditjs/svelte/components/thread-node.svelte
<script>
import Reply from "./reply.svelte"
export let node
</script>

<div class="comment">
    <p>{@html node.text}</p>
    <div class="reply"><Reply {node} /></div>
    <div class="children">
        {#each node.children as child (child.id)}
            <svelte:self node={child} />
        {/each}
    </div>
</div>

// examples/threaditjs/vue/components/thread-node.vue
<template>
    <div class="comment">
        <p v-html="node.text"></p>
        <div class="reply"><thread-reply :node="node"></thread-reply></div>
        <div class="children">
            <thread-node
                v-for="child in node.children"
                v-bind:key="child.id"
                v-bind:node="child"
            ></thread-node>
        </div>
    </div>
</template>

<script>
import ThreadReply from "./thread-reply.vue"

export default {
    name: "thread-node",

    props: ["node"],

    components: {
        ThreadReply,
    },
}
</script>
