// examples/threaditjs/react-hooks-jsx/components/ThreadPreview.js
import React from "react"
import {Link} from "react-router"

export default function ThreadPreview({thread}) {
    return <>
        <p>
            <Link
                to={`/thread/${thread.id}`}
                dangerouslySetInnerHTML={{__html: T.trimTitle(thread.text)}}
            />
        </p>
        <p className="comment_count">{thread.comment_count} comment(s)</p>
        <hr />
    </>
}

// examples/threaditjs/vue/components/thread-preview.vue
<template>
    <p>
        <router-link
            v-bind:to="'/thread/' + thread.id"
            v-html="trimTitle(thread.text)"
        ></router-link>
    </p>
    <p class="comment_count">{{thread.comment_count}} comment(s)</p>
    <hr>
</template>

<script>
export default {
    props: ["thread"],

    methods: {
        trimTitle: (text) => T.trimTitle(text),
    },
}
</script>
