// examples/threaditjs/svelte/components/thread.svelte
<script>
import Layout from "./layout.svelte"
import ThreadNode from "./thread-node.svelte"
import * as api from "../api.mjs"

export let currentRoute
let root

$: title = T.trimTitle(root.text)

async function load(signal) {
    root = (await api.thread(currentRoute.namedParams.id, {signal})).root
}
</script>

<svelte:head>
    <title>ThreaditJS: Svelte | {title}</title>
</svelte:head>

<Layout {load}>
    <ThreadNode node={root} />
</Layout>

// examples/threaditjs/mithril-v2-jsx/components/Thread.jsx
import m from "mithril"
import * as api from "../api.mjs"
import Layout from "./Layout.jsx"
import ThreadNode from "./ThreadNode.jsx"

export default {
    oninit: () => T.time("Thread render"),
    oncreate: () => T.timeEnd("Thread render"),
    view: ({attrs}) => (
        <Layout
            key={attrs.id}
            load={async (signal) => {
                const {root} = await api.thread(attrs.id, {signal})
                document.title = `ThreaditJS: Mithril | ${T.trimTitle(root.text)}`
                return root
            }}
            view={(node) => <ThreadNode node={node} />}
        />
    ),
}
